- job:
    name: oslo.log-src-grenade-devstack
    parent: legacy-dsvm-base
    voting: false
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
    post-run: playbooks/legacy/oslo.log-src-grenade-devstack/post
    required-projects:
      - openstack-dev/grenade
      - openstack-infra/devstack-gate
      - openstack/oslo.log
    run: playbooks/legacy/oslo.log-src-grenade-devstack/run
    timeout: 10800

- project:
    name: openstack/oslo.log
    check:
      jobs:
        - oslo.log-src-grenade-devstack

